name = "nemunasring"
page = "https://dvim.notion.site/Nemunas-Ring-f3e503f979c44b728bc0a9137506432b"

[site]
  [[site.meta]]
  name = "title"
  content = "Nemunas Ring"

  [[site.meta]]
  name = "description"
  content = "Fan-made informational website about Nemunas Ring track and Lithuanian motorsport scene"

  [[site.inject.body.script]]
  type="text/javascript"
  src="https://www.googletagmanager.com/gtag/js?id=G-GL48J6HDBQ"
  async="true"

  [[site.inject.body.script]]
  type="text/javascript"
  inner_html="""
  window.dataLayer = window.dataLayer || [];
  function gtag() { dataLayer.push(arguments); }
  gtag('js', new Date());
  gtag('config', 'G-GL48J6HDBQ');
  """

