#
# Copyright (C) 2020 ArtXIA <https://github.com/artxia>
# <https://github.com/artxia/Action-NotionSite.git>
#

name: Deploy to Pages

on:
  workflow_dispatch:
    inputs:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: addnab/docker-run-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: gcr.io
          image: 2m/loconotion:fix-docker-registry-2m
          options: |
            -v ${{ github.workspace }}/dist:/app/loconotion/dist
            -v ${{ github.workspace }}:/app/loconotion/src
          run: loconotion src/nemunas_ring.toml

      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: dist/Nemunas Ring
          clean: true
